import pytest
from hw3 import tic_tac_toe_checker


@pytest.mark.parametrize("a",
                         [([['o', 'o', '-'],
                            ['o', 'o', '-'],
                            ['x', 'o', 'x']]),
                          ([['o', 'o', 'x'],
                            ['-', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ([['o', '-', 'x'],
                            ['o', 'o', 'x'],
                            ['x', 'o', 'x']]),
                          ([['o', 'o', 'x'],
                            ['-', 'o', 'o'],
                            ['x', '-', 'x']]),
                          ([['o', 'o', 'o'],
                            ['o', '-', 'x'],
                            ['x', 'o', 'x']]),
                          ([['o', 'o', 'x'],
                            ['-', 'o', 'o'],
                            ['x', 'o', '-']]),
                          ([['o', 'o', 'o'],
                            ['o', '-', '-'],
                            ['x', 'o', 'x']]),
                          ([['-', 'o', 'x'],
                            ['x', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ])
def test_tic_tac_toe_checker_unfinished(a):
    assert tic_tac_toe_checker(a) == 'unfinished'


@pytest.mark.parametrize("a",
                         [([['o', 'o', 'x'],
                            ['o', 'x', 'x'],
                            ['x', 'o', 'x']]),
                          ([['x', 'o', 'x'],
                            ['x', 'x', 'o'],
                            ['x', 'o', 'x']]),
                          ([['o', 'x', 'x'],
                            ['o', 'o', 'x'],
                            ['x', 'o', 'x']]),
                          ([['o', 'o', 'x'],
                            ['x', 'o', 'o'],
                            ['x', 'x', 'x']]),
                          ([['o', 'x', 'o'],
                            ['o', 'x', 'x'],
                            ['x', 'x', 'x']]),
                          ([['o', 'o', 'x'],
                            ['o', 'x', 'o'],
                            ['x', 'o', 'o']]),
                          ([['o', 'o', 'x'],
                            ['o', 'x', 'x'],
                            ['x', 'o', 'x']]),
                          ([['x', 'x', 'x'],
                            ['x', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ])
def test_tic_tac_toe_checker_x_wins(a):
    assert tic_tac_toe_checker(a) == 'x wins'


@pytest.mark.parametrize("a",
                         [([['o', 'o', 'o'],
                            ['o', 'x', 'x'],
                            ['x', 'o', 'x']]),
                          ([['x', 'o', 'x'],
                            ['o', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ([['o', 'x', 'x'],
                            ['o', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ([['o', 'o', 'x'],
                            ['x', 'o', 'o'],
                            ['x', 'x', 'o']]),
                          ([['o', 'x', 'o'],
                            ['o', 'x', 'o'],
                            ['x', 'o', 'o']]),
                          ([['o', 'o', 'o'],
                            ['o', 'x', 'o'],
                            ['x', 'o', 'o']]),
                          ([['o', 'o', 'x'],
                            ['o', 'x', 'x'],
                            ['o', 'o', 'o']]),
                          ([['o', 'x', 'x'],
                            ['o', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ])
def test_tic_tac_toe_checker_o_wins(a):
    assert tic_tac_toe_checker(a) == 'o wins'


@pytest.mark.parametrize("a",
                         [([['o', 'o', 'o'],
                            ['o', 'x', 'x'],
                            ['x', 'x', 'x']]),
                          ([['x', 'x', 'x'],
                            ['o', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ([['o', 'x', 'x'],
                            ['o', 'o', 'o'],
                            ['x', 'x', 'x']]),
                          ([['x', 'o', 'x'],
                            ['x', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ([['o', 'x', 'o'],
                            ['o', 'x', 'o'],
                            ['x', 'x', 'o']]),
                          ([['o', 'x', 'o'],
                            ['o', 'x', 'o'],
                            ['x', 'x', 'o']]),
                          ([['o', 'o', 'x'],
                            ['o', 'x', 'x'],
                            ['o', 'o', 'x']]),
                          ([['x', 'x', 'x'],
                            ['o', 'o', 'o'],
                            ['x', 'o', 'x']]),
                          ])
def test_tic_tac_toe_checker_o_wins(a):
    assert tic_tac_toe_checker(a) == 'draw '
